# Generated by Django 2.2.4 on 2019-11-25 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suggest', '0002_auto_20191126_0526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suggestion',
            name='depressed_level',
        ),
    ]
