# Generated by Django 2.2.4 on 2019-11-25 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggest', '0003_remove_suggestion_depressed_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suggestion',
            name='score',
        ),
        migrations.AddField(
            model_name='suggestion',
            name='depressed_level',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
